package org.angnysa.autodb.metadata.api;

public interface Column {
    Table getTable();
    String getName();
    String getType();
    String getDescription();
    boolean isMandatory();
    Integer getMaxLength();
    Integer getNumFraction();
    Integer getRadix();
    boolean isAutoGenerated();
}
